export { default as Avatar } from './Avatar'
export { default as CommonPage } from './CommonPage'
export { default as Trigger} from './Trigger'
export { default as Tag } from './Tag'
export { default as Loading } from './Loading'